const moviesData = {
    movies: [
        {
            id: 1,
            title: "Animais Fantásticos e Onde Habitam",
            description: "O magizoologista Newt Scamander chega à Nova York com uma misteriosa maleta repleta de criaturas mágicas.",
            synopsis: "Em 1926, o magizoologista Newt Scamander chega a Nova York com uma maleta mágica contendo criaturas fantásticas. Após um incidente que liberta algumas delas, ele se une a Jacob Kowalski, um No-Maj, e a uma bruxa chamada Queenie para capturá-las, enquanto enfrenta uma crescente ameaça obscura que pode desencadear uma guerra entre o mundo mágico e o não-mágico.",
            img: "public2/images/animaisfantasticos.jpg",
            year: 2016,
            duration: "2h 13min",
            genres: ["Fantasia", "Aventura"],
            rating: "74%",
            cast: "Eddie Redmayne, Katherine Waterston, Dan Fogler",
            director: "David Yates",
            trailer: "https://www.youtube.com/embed/ViuDsy7yb8M",
            curiosities: "Este filme introduziu o universo mágico de J.K. Rowling fora de Hogwarts!"
        },
        {
            id: 2,
            title: "Animais Fantásticos: Os Crimes de Grindelwald",
            description: "Newt Scamander retorna para enfrentar o perigoso bruxo Gellert Grindelwald.",
            synopsis: "Em 1927, após escapar da custódia, Gellert Grindelwald busca reunir seguidores para dominar o mundo não-mágico. Newt Scamander é recrutado pelo Ministério da Magia para impedi-lo, enfrentando dilemas pessoais e revelações sobre seu passado enquanto a guerra entre bruxos se intensifica.",
            img: "public2/images/animaisfantasticos2.jpg",
            year: 2018,
            duration: "2h 14min",
            genres: ["Fantasia", "Aventura", "Drama"],
            rating: "64%", // Corrigido de 67% para 64%
            cast: "Eddie Redmayne, Jude Law, Johnny Depp",
            director: "David Yates",
            trailer: "https://www.youtube.com/embed/VMp6m3nCfow",
            curiosities: "Johnny Depp foi substituído por Mads Mikkelsen como Grindelwald no terceiro filme da série."
        },
        {
            id: 3,
            title: "Animais Fantásticos: Os Segredos de Dumbledore",
            description: "A jornada final para derrotar Grindelwald começa com novos aliados.",
            synopsis: "Em 1930, Albus Dumbledore confia a Newt Scamander a missão de liderar uma equipe diversa contra Gellert Grindelwald, que está cada vez mais próximo de tomar o controle do mundo mágico. A busca por segredos revela alianças inesperadas e sacrifícios inevitáveis.",
            img: "public2/images/animaisfantasticos3.jpg",
            year: 2022,
            duration: "2h 22min",
            genres: ["Fantasia", "Aventura"],
            rating: "76%", // Corrigido de 71% para 76%
            cast: "Eddie Redmayne, Jude Law, Mads Mikkelsen",
            director: "David Yates",
            trailer: "https://www.youtube.com/embed/oP_5lKTYD5Y",
            curiosities: "Este filme explora mais a fundo a relação entre Dumbledore e Grindelwald, que foi apenas sugerida nos filmes anteriores."
        },
        {
            id: 4,
            title: "Harry Potter e a Pedra Filosofal",
            description: "Harry descobre ser um bruxo e entra em Hogwarts.",
            synopsis: "Harry Potter, um órfão criado por tios abusivos, descobre aos 11 anos que é um bruxo famoso. Ele é aceito em Hogwarts, onde aprende magia, faz amigos como Rony e Hermione, e enfrenta o retorno de Lorde Voldemort, que busca a Pedra Filosofal para recuperar seu poder.",
            img: "public2/images/harrypotter1.jpg",
            year: 2001,
            duration: "2h 32min",
            genres: ["Fantasia", "Aventura", "Família"],
            rating: "81%", // Corrigido de 92% para 81%
            cast: "Daniel Radcliffe, Rupert Grint, Emma Watson",
            director: "Chris Columbus",
            trailer: "https://www.youtube.com/embed/VyHV0BRtdxo",
            curiosities: "O ator Daniel Radcliffe tinha apenas 11 anos quando foi escalado para o papel de Harry Potter!"
        },
        {
            id: 5,
            title: "Harry Potter e a Câmara Secreta",
            description: "Harry retorna a Hogwarts e descobre a Câmara Secreta.",
            synopsis: "No segundo ano em Hogwarts, Harry Potter e seus amigos investigam misteriosos ataques a alunos, descobrindo que a Câmara Secreta foi aberta. Harry enfrenta o jovem Tom Riddle, o futuro Voldemort, e um basilisco gigante para salvar a escola e sua amiga Gina Weasley.",
            img: "public2/images/harrypotter2.jpg",
            year: 2002,
            duration: "2h 41min",
            genres: ["Fantasia", "Aventura", "Mistério"],
            rating: "82%", // Corrigido de 89% para 82%
            cast: "Daniel Radcliffe, Rupert Grint, Emma Watson",
            director: "Chris Columbus",
            trailer: "https://www.youtube.com/embed/1gIaa2T4L0U",
            curiosities: "O carro voador usado no filme, um Ford Anglia, foi realmente destruído durante as filmagens!"
        },
        {
            id: 6,
            title: "Harry Potter e o Prisioneiro de Azkaban",
            description: "Harry descobre sobre Sirius Black e os segredos de seus pais.",
            synopsis: "No terceiro ano, Harry descobre que Sirius Black, um prisioneiro fugitivo de Azkaban, está atrás dele. Com a ajuda de seus amigos e do novo professor Lupin, ele enfrenta dementadores e descobre segredos sobre o passado de seus pais, mudando sua percepção sobre sua própria história.",
            img: "public2/images/harrypotter3.jpg",
            year: 2004,
            duration: "2h 22min",
            genres: ["Fantasia", "Aventura", "Mistério"],
            rating: "90%",
            cast: "Daniel Radcliffe, Rupert Grint, Emma Watson",
            director: "Alfonso Cuarón",
            trailer: "https://www.youtube.com/embed/lAxgztbYBbs",
            curiosities: "Este foi o primeiro filme da série dirigido por Alfonso Cuarón, trazendo um tom mais sombrio à franquia."
        },
        {
            id: 7,
            title: "Harry Potter e o Cálice de Fogo",
            description: "Harry é escolhido para competir no Torneio Tribruxo.",
            synopsis: "No quarto ano, Harry é misteriosamente inscrito no perigoso Torneio Tribruxo, enfrentando desafios mortais ao lado de outros campeões. Ele descobre que Lorde Voldemort está retornando ao poder, culminando em um confronto que muda o curso de sua vida para sempre.",
            img: "public2/images/harrypotter4.jpg",
            year: 2005,
            duration: "2h 37min",
            genres: ["Fantasia", "Aventura", "Ação"],
            rating: "88%",
            cast: "Daniel Radcliffe, Rupert Grint, Emma Watson",
            director: "Mike Newell",
            trailer: "https://www.youtube.com/embed/3EGojp4A9uI",
            curiosities: "Robert Pattinson, que interpreta Cedric Diggory, mais tarde se tornaria famoso como Edward Cullen em Crepúsculo!"
        },
        {
            id: 8,
            title: "Harry Potter e a Ordem da Fênix",
            description: "Harry forma a Armada de Dumbledore contra Voldemort.",
            synopsis: "Com o retorno de Voldemort, Harry enfrenta a descrença do mundo mágico e do Ministério da Magia. Ele forma a Armada de Dumbledore com seus amigos para se preparar para a guerra, enquanto lida com a chegada da opressiva Dolores Umbridge em Hogwarts.",
            img: "public2/images/harrypotter5.jpg",
            year: 2007,
            duration: "2h 18min",
            genres: ["Fantasia", "Aventura", "Drama"],
            rating: "78%", // Corrigido de 87% para 78%
            cast: "Daniel Radcliffe, Rupert Grint, Emma Watson",
            director: "David Yates",
            trailer: "https://www.youtube.com/embed/y6ZW7KXaXYk",
            curiosities: "Imelda Staunton, que interpreta Dolores Umbridge, foi amplamente elogiada por sua atuação como a vilã odiada."
        },
        {
            id: 9,
            title: "Harry Potter e o Enigma do Príncipe",
            description: "Harry descobre mais sobre o passado de Voldemort.",
            synopsis: "Enquanto Voldemort ganha força, Harry e Dumbledore investigam as memórias do passado de Tom Riddle, descobrindo as Horcruxes. Em Hogwarts, Harry lida com novos desafios emocionais e a crescente ameaça de Draco Malfoy, culminando em uma tragédia devastadora.",
            img: "public2/images/harrypotter6.jpg",
            year: 2009,
            duration: "2h 33min",
            genres: ["Fantasia", "Aventura", "Drama"],
            rating: "84%",
            cast: "Daniel Radcliffe, Rupert Grint, Emma Watson",
            director: "David Yates",
            trailer: "https://www.youtube.com/embed/JKLFSuoxX1E",
            curiosities: "O filme foi indicado ao Oscar de Melhor Fotografia, destacando seu estilo visual mais sombrio."
        },
        {
            id: 10,
            title: "Harry Potter e as Relíquias da Morte: Parte 1",
            description: "Harry, Rony e Hermione começam a caça às Horcruxes.",
            synopsis: "Com Voldemort no poder, Harry, Rony e Hermione abandonam Hogwarts para caçar as Horcruxes, objetos que contêm partes da alma do vilão. Eles enfrentam perigos, isolamento e dúvidas, enquanto a guerra no mundo mágico se intensifica ao seu redor.",
            img: "public2/images/harrypotter7.jpg",
            year: 2010,
            duration: "2h 26min",
            genres: ["Fantasia", "Aventura", "Drama"],
            rating: "79%", // Corrigido de 86% para 79%
            cast: "Daniel Radcliffe, Rupert Grint, Emma Watson",
            director: "David Yates",
            trailer: "https://www.youtube.com/embed/MxqsmsA8y5k",
            curiosities: "Este foi o primeiro filme de Harry Potter dividido em duas partes para adaptar o último livro com mais detalhes."
        },
        {
            id: 11,
            title: "Harry Potter e as Relíquias da Morte: Parte 2",
            description: "A batalha final entre Harry e Voldemort acontece em Hogwarts.",
            synopsis: "Harry, Rony e Hermione continuam sua missão de destruir as Horcruxes, levando à batalha final em Hogwarts. Harry descobre seu destino como o Escolhido, enfrentando Voldemort em um confronto épico que decide o futuro do mundo mágico.",
            img: "public2/images/harrypotter8.jpg",
            year: 2011,
            duration: "2h 10min",
            genres: ["Fantasia", "Aventura", "Ação"],
            rating: "96%",
            cast: "Daniel Radcliffe, Rupert Grint, Emma Watson",
            director: "David Yates",
            trailer: "https://www.youtube.com/embed/5NYt1qirBWg",
            curiosities: "O filme arrecadou mais de 1,3 bilhão de dólares em bilheteria mundial, sendo um dos mais bem-sucedidos da franquia!"
        },
        {
            id: 12,
            title: "O Senhor dos Anéis: A Sociedade do Anel",
            description: "Frodo inicia sua jornada com a Sociedade do Anel para destruir o Um Anel.",
            synopsis: "Frodo Bolseiro, um hobbit do Condado, herda o Um Anel de seu tio Bilbo. Com a ajuda de Gandalf, Aragorn, Legolas, Gimli e outros, ele forma a Sociedade do Anel para levá-lo até Mordor e destruí-lo, enfrentando os perigos de Sauron e seus servos.",
            img: "public2/images/senhordosaneis1.jpg",
            year: 2001,
            duration: "2h 58min",
            genres: ["Fantasia", "Aventura", "Ação"],
            rating: "91%", // Corrigido de 92% para 91%
            cast: "Elijah Wood, Ian McKellen, Viggo Mortensen",
            director: "Peter Jackson",
            trailer: "https://www.youtube.com/embed/V75dMMIW2B4",
            curiosities: "O filme foi indicado a 13 Oscars e venceu 4, incluindo Melhor Fotografia!"
        },
        {
            id: 13,
            title: "O Senhor dos Anéis: As Duas Torres",
            description: "Frodo e Sam continuam sua jornada, enquanto a Sociedade se divide.",
            synopsis: "A Sociedade do Anel se separa: Frodo e Sam seguem para Mordor com Gollum como guia, enquanto Aragorn, Legolas e Gimli se unem aos Rohirrim para enfrentar Saruman e seus exércitos em Helm's Deep, em uma das maiores batalhas da Terra Média.",
            img: "public2/images/senhordosaneis2.jpg",
            year: 2002,
            duration: "2h 59min",
            genres: ["Fantasia", "Aventura", "Ação"],
            rating: "95%",
            cast: "Elijah Wood, Ian McKellen, Viggo Mortensen",
            director: "Peter Jackson",
            trailer: "https://www.youtube.com/embed/LbfMDwc4azU",
            curiosities: "A batalha de Helm's Deep levou meses para ser filmada e usou mais de 1.000 figurantes!"
        },
        {
            id: 14,
            title: "O Senhor dos Anéis: O Retorno do Rei",
            description: "Frodo e Sam enfrentam perigos para destruir o Anel, enquanto a batalha final acontece em Gondor.",
            synopsis: "Em uma jornada épica, Frodo e Sam, guiados por Gollum, enfrentam os perigos de Mordor para destruir o Um Anel na Montanha da Perdição. Enquanto isso, Aragorn, Legolas, Gimli e Gandalf lideram a batalha final em Gondor contra as forças de Sauron, decidindo o destino da Terra Média.",
            img: "public2/images/senhordosaneis3.jpg",
            year: 2003,
            duration: "3h 21min",
            genres: ["Fantasia", "Aventura", "Ação"],
            rating: "97%",
            cast: "Elijah Wood, Viggo Mortensen, Ian McKellen",
            director: "Peter Jackson",
            trailer: "https://www.youtube.com/embed/r5X-hFf6qEc",
            curiosities: "Este filme ganhou 11 Oscars, empatando com Titanic e Ben-Hur como o maior vencedor da história!"
        },
        {
            id: 15,
            title: "O Hobbit: Uma Jornada Inesperada",
            description: "Bilbo Baggins embarca em uma aventura com Gandalf e anões.",
            synopsis: "Bilbo Baggins, um hobbit pacato, é convencido por Gandalf a se juntar a uma companhia de anões liderada por Thorin Escudo de Carvalho para recuperar o Reino de Erebor das garras do dragão Smaug, iniciando uma jornada cheia de perigos e descobertas.",
            img: "public2/images/hobbit1.jpg",
            year: 2012,
            duration: "2h 49min",
            genres: ["Fantasia", "Aventura"],
            rating: "85%",
            cast: "Martin Freeman, Ian McKellen, Richard Armitage",
            director: "Peter Jackson",
            trailer: "https://www.youtube.com/embed/9n4skIu4f-c",
            curiosities: "Martin Freeman foi escalado como Bilbo após Peter Jackson atrasar as filmagens para esperá-lo!"
        },
        {
            id: 16,
            title: "O Hobbit: A Desolação de Smaug",
            description: "Bilbo e os anões enfrentam perigos para chegar a Erebor.",
            synopsis: "Bilbo, Gandalf e os anões continuam sua jornada rumo a Erebor, enfrentando aranhas gigantes, elfos de Mirkwood e os homens de Cidade do Lago. Bilbo descobre o Um Anel e usa suas habilidades para confrontar o dragão Smaug, enquanto forças sombrias se aproximam.",
            img: "public2/images/hobbit2.jpg",
            year: 2013,
            duration: "2h 41min",
            genres: ["Fantasia", "Aventura"],
            rating: "88%",
            cast: "Martin Freeman, Ian McKellen, Richard Armitage",
            director: "Peter Jackson",
            trailer: "https://www.youtube.com/embed/OPVWy1tFXuc",
            curiosities: "O dragão Smaug foi dublado por Benedict Cumberbatch, que também fez captura de movimento para o personagem!"
        },
        {
            id: 17,
            title: "O Hobbit: A Batalha dos Cinco Exércitos",
            description: "A batalha final por Erebor reúne homens, elfos e anões.",
            synopsis: "Após despertar Smaug, Bilbo e os anões enfrentam as consequências enquanto o dragão ataca Cidade do Lago. Uma guerra épica entre homens, elfos, anões, orcs e outras criaturas decide o destino de Erebor, enquanto Bilbo tenta evitar um conflito maior.",
            img: "public2/images/hobbit3.jpg",
            year: 2014,
            duration: "2h 24min",
            genres: ["Fantasia", "Aventura", "Ação"],
            rating: "84%", // Corrigido de 90% para 84%
            cast: "Martin Freeman, Ian McKellen, Richard Armitage",
            director: "Peter Jackson",
            trailer: "https://www.youtube.com/embed/iVAgTiBrrDA",
            curiosities: "Este filme marca o fim da jornada de Peter Jackson na Terra Média, iniciada com O Senhor dos Anéis!"
        }
    ]
};